<link rel="stylesheet" href="/css/volt/modules/feed.css">
<div class="content-wrapper">
    <div class="container layout-single">
        <!-- O container onde o JS injetará o feed -->
        <div id="feed-app" class="volt-animate">
            <div class="text-center p-6 mt-12">
                <span class="text-muted">Carregando ideias incríveis...</span>
            </div>
        </div>
    </div>
</div>
<script src="/js/volt/modules/feed.js"></script>