; Configurações de Erro (Perfeito para seu ambiente de teste)
error_reporting = E_ALL
display_errors = On

; Configuração de Sessão com Redis
session.save_handler = redis
; Usamos "redis" como host porque é o nome do container no seu docker-compose.yml
session.save_path = "tcp://redis:6379"

; Configurações de Sentry em ambiente Dev. Exibe dados sensíveis para facilitar o desenvolvimento, mas cuidado em produção! Lá deve ser retirado ou ajustado para não expor informações sensíveis.
zend.exception_ignore_args = Off