services:
  - type: web
    name: best-idea-app
    runtime: docker
    plan: free
    # O Render detectará automaticamente o seu Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: best-idea-redis
          property: connectionString

databases:
  - name: best-idea-redis
    type: redis
    plan: free
    ipAllowList: [] # Permite acesso interno do seu app